/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ExpenseChart: typeof import('./components/ExpenseChart.vue')['default']
    ExpenseFilter: typeof import('./components/ExpenseFilter.vue')['default']
    ExpenseTable: typeof import('./components/ExpenseTable.vue')['default']
    GLAccountExpensesChart: typeof import('./components/GLAccountExpensesChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Main: typeof import('./pages/Main.vue')['default']
    MonthExpensesChart: typeof import('./components/MonthExpensesChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
